name: asdf-java Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    steps:
    - uses: actions/checkout@v1
    - name: Install asdf
      run: git clone --quiet https://github.com/asdf-vm/asdf.git
    - name: Run tests
      run: |
        . asdf/asdf.sh
        asdf plugin-test java $GITHUB_WORKSPACE
